criteria:
  novelty: "qwen/qwen3-4b:free"
  scientificity: "qwen/qwen3-4b:free"
  readability: "qwen/qwen3-4b:free"
  complexity: "qwen/qwen3-4b:free"

review:
  draft: "qwen/qwen3-4b:free"

baseline: "qwen/qwen3-4b:free"